backend:
        name: git-gateway
        branch: master
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
        - name: "colors"
          label: "Colors"
          folder: "data/posts"
          create: true
          filter: {field: "category", value: "Colors"}
          fields:
                - label: "Colors"
                  name: "colors"
                  widget: "palette"
                  fields:
                        - {label: "Color", name: "color", widget: "string"}
                        - {label: "Width", name: "width", widget: "number"}
                - {label: "Title", name: "title", widget: "string"}
                - {label: "Date", name: "date", widget: "date"}
                - {label: "Category", name: "category", value: "Colors", widget: "hidden"}
                - {label: "Blog Post Content", name: "body", widget: "markdown"}

